var cars=[
	{
		id:1,
		picurl:'../../images/carList/car.png',
		name:'桑坦纳2017新款轿车1',
		carType:'商务车',
		brand:'德国大众桑塔纳',
		seat:'五座',
		price:900,
		rentType:'自驾',
		companyName:'山西神州租车服务有限公司',
		companyAddress:'山西省太原市尖草坪区学院路988',
		tel:'0351-7856463'
	},
	{
		id:2,
		picurl:'../../images/carList/car.png',
		name:'桑坦纳2017新款轿车2',
		carType:'商务车',
		brand:'德国大众桑塔纳',
		seat:'五座',
		price:900,
		rentType:'自驾',
		companyName:'山西神州租车服务有限公司',
		companyAddress:'山西省太原市尖草坪区学院路988',
		tel:'0351-7856463'
	},{
		id:3,
		picurl:'../../images/carList/car.png',
		name:'桑坦纳2017新款轿车3',
		carType:'商务车',
		brand:'德国大众桑塔纳',
		seat:'五座',
		price:900,
		rentType:'自驾',
		companyName:'山西神州租车服务有限公司',
		companyAddress:'山西省太原市尖草坪区学院路988',
		tel:'0351-7856463'
	}
];
export default cars;